import ProductsNavigation from "@/app/components/ProductsNavigation/ProductsNavigation";
import { getProducts } from "@/lib/getProducts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { products } = await getProducts();

  return (
    <div className="flex p-4">
      
      {children}
    </div>
  );
}
